### ISSUE TITLE
tabulo: command not found

### ISSUE THREAD

**Issue by oliverbj** [interviewBubble/Tabulo#14]
When installing Tabulo, I get below:

```
Installing collected packages: tabulo
  Attempting uninstall: tabulo
    Found existing installation: tabulo 0.2.4.dev0
    Uninstalling tabulo-0.2.4.dev0:
      Successfully uninstalled tabulo-0.2.4.dev0
  Running setup.py develop for tabulo
Successfully installed tabulo
```

After this, when running below from my CLI:

```
tabulo --help
```

I get below error:

> -bash: tabulo: command not found

I am running Python on Mac OS X. What am I doing wrong?

**Comment by Vanchristoph3r** [comment]
Maybe you're missing a variable in your path, I used a virtualenv and works perfect
