### ISSUE TITLE
Not able to predict default page_8-min.jpg using Postman

### ISSUE THREAD

**Issue by akshaydp1995** [interviewBubble/Tabulo#4]
I've downloaded a JPEG into the Tabulo directory (that I've cloned) and tried to run PostMan by importing the curl command onto PostMan
Key as 'image'
Value as '2_resized.jpg'

The error is 
{
    "error": "Missing image"
}

400 BAD REQUEST Error

**Comment by interviewBubble** [comment]
heck this: https://github.com/interviewBubble/Tabulo/blob/master/README.md#header-section

**Comment by akshaydp1995** [comment]
Yes of course I did that. Same error.

**Comment by akshaydp1995** [comment]
I've followed the following steps:
1. Entered a virtual environment on my Ubuntu 18.04 systems
2. pip install tensorflow
3. git clone https://github.com/interviewBubble/Tabulo.git
4. cd Tabulo
5. pip install -e .
6. tabulo --help (Works)
7. Downloaded PostMan
8. PostMan - New tab - Import - Paste Raw Link - Pasted the following:
curl -X POST \
  http://localhost:5000/api/fasterrcnn/predict/ \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 70478bd2-e1e8-442f-b0bf-ea5ecf7bf4d8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F image=@/path/to/image/page_8-min.jpg
9. Changed the directory for the last line to /docs/images/page_8-min.jpg
10. Clicked Send on PostMan 
11. Error is 
{
    "error": "Missing image"
}

**Comment by interviewBubble** [comment]
Now you have to download the pre-trained model to get started:
https://github.com/interviewBubble/Tabulo#7-working-with-pretrained-models

**Comment by akshaydp1995** [comment]
Yes, downloaded that too. tabula checkpoint list already shows 1 local checkpoint.

**Comment by interviewBubble** [comment]
You have to run also:

Now run server using this command: 
`tabulo sever web --checkpoint 6aac7a1e8a8e`

**Comment by akshaydp1995** [comment]
Yes did that as well

**Comment by interviewBubble** [comment]
```
curl -X POST
http://localhost:5000/api/fasterrcnn/predict/
-H 'Content-Type: application/x-www-form-urlencoded'
-H 'Postman-Token: 70478bd2-e1e8-442f-b0bf-ea5ecf7bf4d8'
-H 'cache-control: no-cache'
-H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
-F image=@/path/to/image/page_8-min.jpg
```
This curl command you should use cmd for that.

**Comment by interviewBubble** [comment]
I have given two ways to use service
1. Using curl command on Command Prompt.
2. Using Postman.

**Comment by Denrose11** [comment]
Hi, I am also getting:
{
    "error":"Missing image"
}
![image](https://user-images.githubusercontent.com/45919716/75015227-1d400900-54ae-11ea-808d-5459d42cc0c3.png)

pls help!

can you help me running curl commands too

![image](https://user-images.githubusercontent.com/45919716/75015308-4f516b00-54ae-11ea-83fd-dccb4174b2c4.png)

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/82720520-f5e41c80-9ce6-11ea-8d9d-aba9fce4d0ce.png)
I`m also meeting this issue
