### ISSUE TITLE
clarificatons..

### ISSUE THREAD

**Issue by chansekar** [interviewBubble/Tabulo#7]
Hi ,

I have few questions on tabulo

1. i am unable to download the checkpoint which is trained on tables i am able to see a cooc dataset faster rcnn and ssd.

2. how does tabulo work? i mean i dont see any installation of tesseract how is the able to display the characters from a table image?

Regards
Sekar

**Comment by interviewBubble** [comment]
1. I have given a link. it is working for others. I don't know what is happening in your end.
2. yes you have to install tesseract.

**Comment by chansekar** [comment]
Thanks,

it looked like some kind of browser issue, i had to reinstall firefoax and it worked, strange though.
